language: node_js
dist: xenial
sudo: required
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
matrix:
  fast_finish: true
os:
  - linux
  - centos
  - osx
  - windows
env:
  - NODE_ENV=travis
services:
  - mongodb
  - xvfb
addons:
  apt:
    packages:
    - g++
    - gcc
    - clang
  chrome: stable
before_install:
#   - npm install webdriver-manager -g && webdriver-manager update
  - npm install nsp -g
#  - npm install snyk -g
  - 'export PATH=$PATH:/usr/lib/chromium-browser/'
  - 'export DISPLAY=:99.0'
#before_script:
#  - snyk auth $SNYK_TOKEN
#  - snyk test
after_script:
  - nsp check
#  - snyk test
  - gulp test:coverage
  - npm install lcov-result-merger@~1.2.0 -g
  - lcov-result-merger 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js
notifications:
  webhooks:
    urls:
      - $GITTER_IM_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
