version: 2

jobs:
    build:
        working_directory: ~/angularcli
        # The primary container is an instance of the first list image listed. Your build commands run in this container.
        docker:
            - image: circleci/node:6-browsers
              environment:
                  CHROME_BIN: "/usr/bin/google-chrome"
        steps:
            - checkout
            - run:
                name: Install node_modules with npm
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Install angularcli
                command: sudo npm install -g @angular/cli@latest
            - run:
                name: Install angularcli in devDependencies
                command: npm install --save-dev @angular/cli@latest
            # - run:
            #     name: Run unit tests with karma
            #     command: ng test
            # - store_test_results:
            #     path: test-results.xml
